dataset_name: 'cifar100'
dataset_classes: 100
# Requires to create tfrecord
train_prefix: "train"
valid_prefix: "test"

# Model Save related
model_save_dir: 'model_ckpt' # ckpt file format

# Image preprocessing args
image_height: 72
image_width: 72
image_channel: 3
channel_last: True

# Gradio Inference
gradio_share: True

# TF Server model creator
serving_version: 1