architecture: 'vit'

# Architecture Config
use_mixed_precision: False
batch_size: 16

normalize: "standard"
# Requires to identify upper and lower characters
# To use custom model, set architecture as 'custom'
learning_rate: 0.001
epochs: 100

serving_version: 1


#Visual_Attention
patches: 16
hidden_size: 256
mlp_dim: 1024
num_heads: 4
num_layers: 8
dropout_rate: 0.1
