# Architecture Config
use_mixed_precision: True
batch_size: 128

normalize: "standard"
# Requires to identify upper and lower characters
# To use custom model, set architecture as 'custom'
learning_rate: 0.001
epochs: 100

serving_version: 1


#Visual_Attention
patches: 16
hidden_size: 768
mlp_dim: 3072
num_heads: 12
num_layers: 12
dropout_rate: 0.1

activation: 'gelu'
